// Generated by scripts/emit_hurwitz_degree23_magma_geometry_certificate.py.
// Independent finite-field check of all twelve embeddings of the sextic component.

procedure Must(condition, message)
    if not condition then error message; end if;
end procedure;

F := GF(863153);
P<X1,X2,X3,X4> := PolynomialRing(F, 4, "grevlex");

function CheckPlaneFibre(q, c, N, D, lambda, embedding)
    A<x,y> := PolynomialRing(F, 2);
    FF := FieldOfFractions(A);
    Z<z> := PolynomialRing(FF);
    qz := Evaluate(q, [Z!1, Z!x, Z!y, z]);
    cz := Evaluate(c, [Z!1, Z!x, Z!y, z]);
    remainder := cz mod qz;
    if Degree(remainder) ne 1 then return false, false; end if;
    zvalue := -Coefficient(remainder, 0)/Coefficient(remainder, 1);
    plane := A!Numerator(Resultant(qz, cz));
    nfraction := Evaluate(N, [Z!1, Z!x, Z!y, Z!zvalue]);
    dfraction := Evaluate(D, [Z!1, Z!x, Z!y, Z!zvalue]);
    mapfraction := FF!(nfraction/dfraction);
    nplane := A!Numerator(mapfraction);
    dplane := A!Denominator(mapfraction);
    U<u> := PolynomialRing(F);
    generic_raw := Resultant(plane, nplane - 2*dplane, 2);
    generic_resultant := Evaluate(generic_raw, [u, U!0]);
    branch_plane := nplane - lambda*dplane;
    branch_raw := Resultant(plane, branch_plane, 2);
    branch_resultant := Evaluate(branch_raw, [u, U!0]);
    generic_gcd := GCD(generic_resultant, Derivative(generic_resultant));
    branch_gcd := GCD(branch_resultant, Derivative(branch_resultant));
    common_gcd := GCD(generic_gcd, branch_gcd);
    extra_gcd := branch_gcd div common_gcd;
    geometry_ok := Degree(generic_resultant) eq 42
        and Degree(branch_resultant) eq 42
        and Degree(generic_gcd) eq 6
        and Degree(branch_gcd) eq 14
        and Degree(common_gcd) eq 6
        and Degree(extra_gcd) eq 8
        and GCD(extra_gcd, Derivative(extra_gcd)) eq 1;
    if not geometry_ok then return false, false; end if;
    collision_free := true;
    for item in Factorization(extra_gcd) do
        h := item[1];
        E<alpha> := ext<F | h>;
        V<v> := PolynomialRing(E);
        plane_at_alpha := Evaluate(plane, [V!alpha, v]);
        branch_at_alpha := Evaluate(branch_plane, [V!alpha, v]);
        common_y := GCD(plane_at_alpha, branch_at_alpha);
        if Degree(common_y) ne 1 then collision_free := false; end if;
    end for;
    return true, collision_free;
end function;

all_critical_checks := true;
all_plane_checks := true;
collision_free_embeddings := [];

// Residue embedding 1, a |-> 37926.
q := 0*X1*X1 + 0*X1*X2 + 1*X1*X3 + 1*X1*X4 + 863152*X2*X2 + 863152*X2*X3 + 391121*X2*X4 + 477526*X3*X3 + 194684*X3*X4 + 615503*X4*X4;
c := 0*X1*X1*X1 + 0*X1*X1*X2 + 0*X1*X1*X3 + 118580*X1*X1*X4 + 0*X1*X2*X2 + 0*X1*X2*X3 + 118580*X1*X2*X4 + 0*X1*X3*X3 + 0*X1*X3*X4 + 65857*X1*X4*X4 + 744573*X2*X2*X2 + 78607*X2*X2*X3 + 120392*X2*X2*X4 + 426115*X2*X3*X3 + 723640*X2*X3*X4 + 351347*X2*X4*X4 + 1*X3*X3*X3 + 274558*X3*X3*X4 + 811277*X3*X4*X4 + 701093*X4*X4*X4;
N := 1*X2^2*X3^3 + 342856*X2^4*X3^1 + 149137*X2^5 + 538397*X1^1*X2^1*X3^3 + 514071*X1^1*X2^2*X3^1*X4^1 + 642328*X1^1*X2^2*X3^2 + 74546*X1^1*X2^3*X4^1 + 751465*X1^1*X2^3*X3^1 + 192265*X1^1*X2^4 + 480931*X1^2*X3^3 + 481278*X1^2*X2^1*X3^1*X4^1 + 534274*X1^2*X2^1*X3^2 + 604532*X1^2*X2^2*X4^1 + 735703*X1^2*X2^2*X3^1 + 819641*X1^2*X2^3 + 611063*X1^3*X3^1*X4^1 + 92661*X1^3*X3^2 + 627090*X1^3*X2^1*X4^1 + 255264*X1^3*X2^1*X3^1 + 852165*X1^3*X2^2 + 651401*X1^4*X4^1 + 10988*X1^4*X3^1;
D := 1*X2^2*X3^3 + 742325*X2^3*X3^1*X4^1 + 824287*X2^3*X3^2 + 325865*X2^4*X4^1 + 249424*X2^4*X3^1 + 215065*X2^5 + 398412*X1^1*X2^1*X3^3 + 434002*X1^1*X2^2*X3^1*X4^1 + 169817*X1^1*X2^2*X3^2 + 275353*X1^1*X2^3*X4^1 + 393644*X1^1*X2^3*X3^1 + 37823*X1^1*X2^4 + 372687*X1^2*X3^3 + 668591*X1^2*X2^1*X3^1*X4^1 + 786242*X1^2*X2^1*X3^2 + 735736*X1^2*X2^2*X4^1 + 714601*X1^2*X2^2*X3^1 + 104188*X1^2*X2^3 + 447268*X1^3*X3^1*X4^1 + 604075*X1^3*X3^2 + 163845*X1^3*X2^1*X4^1 + 297728*X1^3*X2^1*X3^1 + 325173*X1^3*X2^2 + 655209*X1^4*X4^1 + 821581*X1^4*X3^1 + 404097*X1^4*X2^1 + 854687*X1^5;
lambda := F!598256;
H := N - lambda*D;
qrow := [ Derivative(q, index) : index in [1..4] ];
crow := [ Derivative(c, index) : index in [1..4] ];
mrow := [ D*Derivative(N, index) - N*Derivative(D, index) : index in [1..4] ];
W := [];
for selected in [1..4] do
    unit := [ P!0 : index in [1..4] ];
    unit[selected] := P!1;
    Append(~W, Determinant(Matrix(P, 4, 4, qrow cat crow cat mrow cat unit)));
end for;
critical_fibre := ideal<P | [q, c, H] cat W>;
hp, regularity := HilbertPolynomial(critical_fibre);
critical_ok := Degree(hp) eq 0 and Coefficient(hp, 0) eq 15;
all_critical_checks := all_critical_checks and critical_ok;
plane_ok, collision_free := CheckPlaneFibre(q, c, N, D, lambda, 1);
all_plane_checks := all_plane_checks and plane_ok;
if collision_free then
    Append(~collision_free_embeddings, 1);
end if;

// Residue embedding 2, a |-> 70524.
q := 0*X1*X1 + 0*X1*X2 + 1*X1*X3 + 1*X1*X4 + 863152*X2*X2 + 863152*X2*X3 + 77923*X2*X4 + 296520*X3*X3 + 582945*X3*X4 + 273297*X4*X4;
c := 0*X1*X1*X1 + 0*X1*X1*X2 + 0*X1*X1*X3 + 859981*X1*X1*X4 + 0*X1*X2*X2 + 0*X1*X2*X3 + 859981*X1*X2*X4 + 0*X1*X3*X3 + 0*X1*X3*X4 + 263259*X1*X4*X4 + 3172*X2*X2*X2 + 754311*X2*X2*X3 + 200479*X2*X2*X4 + 128364*X2*X3*X3 + 7989*X2*X3*X4 + 386778*X2*X4*X4 + 1*X3*X3*X3 + 708669*X3*X3*X4 + 265629*X3*X4*X4 + 405290*X4*X4*X4;
N := 1*X2^2*X3^3 + 591522*X2^4*X3^1 + 388916*X2^5 + 817117*X1^1*X2^1*X3^3 + 250238*X1^1*X2^2*X3^1*X4^1 + 678235*X1^1*X2^2*X3^2 + 402836*X1^1*X2^3*X4^1 + 672035*X1^1*X2^3*X3^1 + 287113*X1^1*X2^4 + 150748*X1^2*X3^3 + 403446*X1^2*X2^1*X3^1*X4^1 + 37686*X1^2*X2^1*X3^2 + 665336*X1^2*X2^2*X4^1 + 515317*X1^2*X2^2*X3^1 + 792822*X1^2*X2^3 + 695523*X1^3*X3^1*X4^1 + 430734*X1^3*X3^2 + 531977*X1^3*X2^1*X4^1 + 597924*X1^3*X2^1*X3^1 + 604161*X1^3*X2^2 + 335560*X1^4*X4^1 + 258992*X1^4*X3^1;
D := 1*X2^2*X3^3 + 699123*X2^3*X3^1*X4^1 + 452309*X2^3*X3^2 + 21160*X2^4*X4^1 + 321707*X2^4*X3^1 + 412205*X2^5 + 671177*X1^1*X2^1*X3^3 + 305621*X1^1*X2^2*X3^1*X4^1 + 350231*X1^1*X2^2*X3^2 + 540267*X1^1*X2^3*X4^1 + 780831*X1^1*X2^3*X3^1 + 554560*X1^1*X2^4 + 813170*X1^2*X3^3 + 235051*X1^2*X2^1*X3^1*X4^1 + 186129*X1^2*X2^1*X3^2 + 76578*X1^2*X2^2*X4^1 + 171383*X1^2*X2^2*X3^1 + 94828*X1^2*X2^3 + 89402*X1^3*X3^1*X4^1 + 507624*X1^3*X3^2 + 551833*X1^3*X2^1*X4^1 + 812733*X1^3*X2^1*X3^1 + 174889*X1^3*X2^2 + 3956*X1^4*X4^1 + 310618*X1^4*X3^1 + 41422*X1^4*X2^1 + 676243*X1^5;
lambda := F!385058;
H := N - lambda*D;
qrow := [ Derivative(q, index) : index in [1..4] ];
crow := [ Derivative(c, index) : index in [1..4] ];
mrow := [ D*Derivative(N, index) - N*Derivative(D, index) : index in [1..4] ];
W := [];
for selected in [1..4] do
    unit := [ P!0 : index in [1..4] ];
    unit[selected] := P!1;
    Append(~W, Determinant(Matrix(P, 4, 4, qrow cat crow cat mrow cat unit)));
end for;
critical_fibre := ideal<P | [q, c, H] cat W>;
hp, regularity := HilbertPolynomial(critical_fibre);
critical_ok := Degree(hp) eq 0 and Coefficient(hp, 0) eq 15;
all_critical_checks := all_critical_checks and critical_ok;
plane_ok, collision_free := CheckPlaneFibre(q, c, N, D, lambda, 2);
all_plane_checks := all_plane_checks and plane_ok;
if collision_free then
    Append(~collision_free_embeddings, 2);
end if;

// Residue embedding 3, a |-> 80491.
q := 0*X1*X1 + 0*X1*X2 + 1*X1*X3 + 1*X1*X4 + 863152*X2*X2 + 863152*X2*X3 + 749327*X2*X4 + 194861*X3*X3 + 188852*X3*X4 + 546990*X4*X4;
c := 0*X1*X1*X1 + 0*X1*X1*X2 + 0*X1*X1*X3 + 40583*X1*X1*X4 + 0*X1*X2*X2 + 0*X1*X2*X3 + 40583*X1*X2*X4 + 0*X1*X3*X3 + 0*X1*X3*X4 + 693502*X1*X4*X4 + 822570*X2*X2*X2 + 764960*X2*X2*X3 + 270036*X2*X2*X4 + 362533*X2*X3*X3 + 91499*X2*X3*X4 + 442114*X2*X4*X4 + 1*X3*X3*X3 + 668659*X3*X3*X4 + 5977*X3*X4*X4 + 189029*X4*X4*X4;
N := 1*X2^2*X3^3 + 504794*X2^4*X3^1 + 204139*X2^5 + 820135*X1^1*X2^1*X3^3 + 692076*X1^1*X2^2*X3^1*X4^1 + 799253*X1^1*X2^2*X3^2 + 7912*X1^1*X2^3*X4^1 + 673395*X1^1*X2^3*X3^1 + 537254*X1^1*X2^4 + 813316*X1^2*X3^3 + 295592*X1^2*X2^1*X3^1*X4^1 + 92948*X1^2*X2^1*X3^2 + 436291*X1^2*X2^2*X4^1 + 529863*X1^2*X2^2*X3^1 + 726872*X1^2*X2^3 + 445512*X1^3*X3^1*X4^1 + 233018*X1^3*X3^2 + 644538*X1^3*X2^1*X4^1 + 388622*X1^3*X2^1*X3^1 + 790416*X1^3*X2^2 + 610812*X1^4*X4^1 + 72737*X1^4*X3^1;
D := 1*X2^2*X3^3 + 836291*X2^3*X3^1*X4^1 + 788372*X2^3*X3^2 + 488584*X2^4*X4^1 + 570682*X2^4*X3^1 + 526676*X2^5 + 251608*X1^1*X2^1*X3^3 + 82284*X1^1*X2^2*X3^1*X4^1 + 373781*X1^1*X2^2*X3^2 + 681902*X1^1*X2^3*X4^1 + 788006*X1^1*X2^3*X3^1 + 276537*X1^1*X2^4 + 788750*X1^2*X3^3 + 299335*X1^2*X2^1*X3^1*X4^1 + 107454*X1^2*X2^1*X3^2 + 275154*X1^2*X2^2*X4^1 + 29417*X1^2*X2^2*X3^1 + 234649*X1^2*X2^3 + 327711*X1^3*X3^1*X4^1 + 688216*X1^3*X3^2 + 323065*X1^3*X2^1*X4^1 + 297383*X1^3*X2^1*X3^1 + 404923*X1^3*X2^2 + 259166*X1^4*X4^1 + 307946*X1^4*X3^1 + 282421*X1^4*X2^1 + 401798*X1^5;
lambda := F!83118;
H := N - lambda*D;
qrow := [ Derivative(q, index) : index in [1..4] ];
crow := [ Derivative(c, index) : index in [1..4] ];
mrow := [ D*Derivative(N, index) - N*Derivative(D, index) : index in [1..4] ];
W := [];
for selected in [1..4] do
    unit := [ P!0 : index in [1..4] ];
    unit[selected] := P!1;
    Append(~W, Determinant(Matrix(P, 4, 4, qrow cat crow cat mrow cat unit)));
end for;
critical_fibre := ideal<P | [q, c, H] cat W>;
hp, regularity := HilbertPolynomial(critical_fibre);
critical_ok := Degree(hp) eq 0 and Coefficient(hp, 0) eq 15;
all_critical_checks := all_critical_checks and critical_ok;
plane_ok, collision_free := CheckPlaneFibre(q, c, N, D, lambda, 3);
all_plane_checks := all_plane_checks and plane_ok;
if collision_free then
    Append(~collision_free_embeddings, 3);
end if;

// Residue embedding 4, a |-> 104480.
q := 0*X1*X1 + 0*X1*X2 + 1*X1*X3 + 1*X1*X4 + 863152*X2*X2 + 863152*X2*X3 + 434421*X2*X4 + 828880*X3*X3 + 62686*X3*X4 + 495037*X4*X4;
c := 0*X1*X1*X1 + 0*X1*X1*X2 + 0*X1*X1*X3 + 809014*X1*X1*X4 + 0*X1*X2*X2 + 0*X1*X2*X3 + 809014*X1*X2*X4 + 0*X1*X3*X3 + 0*X1*X3*X4 + 809854*X1*X4*X4 + 54139*X2*X2*X2 + 628124*X2*X2*X3 + 256838*X2*X2*X4 + 137501*X2*X3*X3 + 695550*X2*X3*X4 + 180306*X2*X4*X4 + 1*X3*X3*X3 + 70718*X3*X3*X4 + 640636*X3*X4*X4 + 239802*X4*X4*X4;
N := 1*X2^2*X3^3 + 726176*X2^4*X3^1 + 706007*X2^5 + 239546*X1^1*X2^1*X3^3 + 100603*X1^1*X2^2*X3^1*X4^1 + 17197*X1^1*X2^2*X3^2 + 853944*X1^1*X2^3*X4^1 + 799969*X1^1*X2^3*X3^1 + 232392*X1^1*X2^4 + 786524*X1^2*X3^3 + 700248*X1^2*X2^1*X3^1*X4^1 + 265898*X1^2*X2^1*X3^2 + 251418*X1^2*X2^2*X4^1 + 209840*X1^2*X2^2*X3^1 + 309832*X1^2*X2^3 + 70700*X1^3*X3^1*X4^1 + 273231*X1^3*X3^2 + 35605*X1^3*X2^1*X4^1 + 570313*X1^3*X2^1*X3^1 + 99429*X1^3*X2^2 + 846161*X1^4*X4^1 + 763724*X1^4*X3^1;
D := 1*X2^2*X3^3 + 86924*X2^3*X3^1*X4^1 + 126095*X2^3*X3^2 + 70114*X2^4*X4^1 + 122592*X2^4*X3^1 + 34239*X2^5 + 112272*X1^1*X2^1*X3^3 + 826501*X1^1*X2^2*X3^1*X4^1 + 654840*X1^1*X2^2*X3^2 + 612654*X1^1*X2^3*X4^1 + 862848*X1^1*X2^3*X3^1 + 860381*X1^1*X2^4 + 536848*X1^2*X3^3 + 18201*X1^2*X2^1*X3^1*X4^1 + 285502*X1^2*X2^1*X3^2 + 296297*X1^2*X2^2*X4^1 + 431089*X1^2*X2^2*X3^1 + 298665*X1^2*X2^3 + 158212*X1^3*X3^1*X4^1 + 823006*X1^3*X3^2 + 439682*X1^3*X2^1*X4^1 + 765501*X1^3*X2^1*X3^1 + 101335*X1^3*X2^2 + 454112*X1^4*X4^1 + 813927*X1^4*X3^1 + 844187*X1^4*X2^1 + 539116*X1^5;
lambda := F!809597;
H := N - lambda*D;
qrow := [ Derivative(q, index) : index in [1..4] ];
crow := [ Derivative(c, index) : index in [1..4] ];
mrow := [ D*Derivative(N, index) - N*Derivative(D, index) : index in [1..4] ];
W := [];
for selected in [1..4] do
    unit := [ P!0 : index in [1..4] ];
    unit[selected] := P!1;
    Append(~W, Determinant(Matrix(P, 4, 4, qrow cat crow cat mrow cat unit)));
end for;
critical_fibre := ideal<P | [q, c, H] cat W>;
hp, regularity := HilbertPolynomial(critical_fibre);
critical_ok := Degree(hp) eq 0 and Coefficient(hp, 0) eq 15;
all_critical_checks := all_critical_checks and critical_ok;
plane_ok, collision_free := CheckPlaneFibre(q, c, N, D, lambda, 4);
all_plane_checks := all_plane_checks and plane_ok;
if collision_free then
    Append(~collision_free_embeddings, 4);
end if;

// Residue embedding 5, a |-> 175882.
q := 0*X1*X1 + 0*X1*X2 + 1*X1*X3 + 1*X1*X4 + 863152*X2*X2 + 863152*X2*X3 + 190694*X2*X4 + 796180*X3*X3 + 525607*X3*X4 + 718884*X4*X4;
c := 0*X1*X1*X1 + 0*X1*X1*X2 + 0*X1*X1*X3 + 100726*X1*X1*X4 + 0*X1*X2*X2 + 0*X1*X2*X3 + 100726*X1*X2*X4 + 0*X1*X3*X3 + 0*X1*X3*X4 + 611870*X1*X4*X4 + 762427*X2*X2*X2 + 423921*X2*X2*X3 + 424900*X2*X2*X4 + 318268*X2*X3*X3 + 638283*X2*X3*X4 + 300931*X2*X4*X4 + 1*X3*X3*X3 + 671045*X3*X3*X4 + 794291*X3*X4*X4 + 18254*X4*X4*X4;
N := 1*X2^2*X3^3 + 503185*X2^4*X3^1 + 472986*X2^5 + 434078*X1^1*X2^1*X3^3 + 530706*X1^1*X2^2*X3^1*X4^1 + 195659*X1^1*X2^2*X3^2 + 515975*X1^1*X2^3*X4^1 + 19750*X1^1*X2^3*X3^1 + 269538*X1^1*X2^4 + 302673*X1^2*X3^3 + 251339*X1^2*X2^1*X3^1*X4^1 + 698316*X1^2*X2^1*X3^2 + 593020*X1^2*X2^2*X4^1 + 158279*X1^2*X2^2*X3^1 + 34444*X1^2*X2^3 + 96075*X1^3*X3^1*X4^1 + 35117*X1^3*X3^2 + 394816*X1^3*X2^1*X4^1 + 250958*X1^3*X2^1*X3^1 + 544859*X1^3*X2^2 + 577751*X1^4*X4^1 + 318294*X1^4*X3^1;
D := 1*X2^2*X3^3 + 606817*X2^3*X3^1*X4^1 + 235853*X2^3*X3^2 + 422761*X2^4*X4^1 + 93815*X2^4*X3^1 + 310950*X2^5 + 816190*X1^1*X2^1*X3^3 + 732555*X1^1*X2^2*X3^1*X4^1 + 647448*X1^1*X2^2*X3^2 + 266257*X1^1*X2^3*X4^1 + 42097*X1^1*X2^3*X3^1 + 830552*X1^1*X2^4 + 725922*X1^2*X3^3 + 607562*X1^2*X2^1*X3^1*X4^1 + 726983*X1^2*X2^1*X3^2 + 461724*X1^2*X2^2*X4^1 + 107378*X1^2*X2^2*X3^1 + 148703*X1^2*X2^3 + 197063*X1^3*X3^1*X4^1 + 314689*X1^3*X3^2 + 467801*X1^3*X2^1*X4^1 + 745968*X1^3*X2^1*X3^1 + 663903*X1^3*X2^2 + 45825*X1^4*X4^1 + 785788*X1^4*X3^1 + 580279*X1^4*X2^1 + 845024*X1^5;
lambda := F!501901;
H := N - lambda*D;
qrow := [ Derivative(q, index) : index in [1..4] ];
crow := [ Derivative(c, index) : index in [1..4] ];
mrow := [ D*Derivative(N, index) - N*Derivative(D, index) : index in [1..4] ];
W := [];
for selected in [1..4] do
    unit := [ P!0 : index in [1..4] ];
    unit[selected] := P!1;
    Append(~W, Determinant(Matrix(P, 4, 4, qrow cat crow cat mrow cat unit)));
end for;
critical_fibre := ideal<P | [q, c, H] cat W>;
hp, regularity := HilbertPolynomial(critical_fibre);
critical_ok := Degree(hp) eq 0 and Coefficient(hp, 0) eq 15;
all_critical_checks := all_critical_checks and critical_ok;
plane_ok, collision_free := CheckPlaneFibre(q, c, N, D, lambda, 5);
all_plane_checks := all_plane_checks and plane_ok;
if collision_free then
    Append(~collision_free_embeddings, 5);
end if;

// Residue embedding 6, a |-> 221239.
q := 0*X1*X1 + 0*X1*X2 + 1*X1*X3 + 1*X1*X4 + 863152*X2*X2 + 863152*X2*X3 + 342970*X2*X4 + 569079*X3*X3 + 272032*X3*X4 + 42925*X4*X4;
c := 0*X1*X1*X1 + 0*X1*X1*X2 + 0*X1*X1*X3 + 382357*X1*X1*X4 + 0*X1*X2*X2 + 0*X1*X2*X3 + 382357*X1*X2*X4 + 0*X1*X3*X3 + 0*X1*X3*X4 + 570868*X1*X4*X4 + 480796*X2*X2*X2 + 27651*X2*X2*X3 + 484836*X2*X2*X4 + 708614*X2*X3*X3 + 404570*X2*X3*X4 + 346880*X2*X4*X4 + 1*X3*X3*X3 + 816413*X3*X3*X4 + 123727*X3*X4*X4 + 490650*X4*X4*X4;
N := 1*X2^2*X3^3 + 437310*X2^4*X3^1 + 749143*X2^5 + 616475*X1^1*X2^1*X3^3 + 705632*X1^1*X2^2*X3^1*X4^1 + 148317*X1^1*X2^2*X3^2 + 811279*X1^1*X2^3*X4^1 + 317887*X1^1*X2^3*X3^1 + 608273*X1^1*X2^4 + 624890*X1^2*X3^3 + 80865*X1^2*X2^1*X3^1*X4^1 + 203091*X1^2*X2^1*X3^2 + 471536*X1^2*X2^2*X4^1 + 717968*X1^2*X2^2*X3^1 + 157581*X1^2*X2^3 + 710152*X1^3*X3^1*X4^1 + 759482*X1^3*X3^2 + 61009*X1^3*X2^1*X4^1 + 86990*X1^3*X2^1*X3^1 + 313518*X1^3*X2^2 + 618582*X1^4*X4^1 + 549635*X1^4*X3^1;
D := 1*X2^2*X3^3 + 16795*X2^3*X3^1*X4^1 + 760163*X2^3*X3^2 + 56420*X2^4*X4^1 + 836502*X2^4*X3^1 + 851997*X2^5 + 604699*X1^1*X2^1*X3^3 + 596556*X1^1*X2^2*X3^1*X4^1 + 364953*X1^1*X2^2*X3^2 + 2538*X1^1*X2^3*X4^1 + 612688*X1^1*X2^3*X3^1 + 474813*X1^1*X2^4 + 365936*X1^2*X3^3 + 47385*X1^2*X2^1*X3^1*X4^1 + 751153*X1^2*X2^1*X3^2 + 703840*X1^2*X2^2*X4^1 + 216245*X1^2*X2^2*X3^1 + 448114*X1^2*X2^3 + 361636*X1^3*X3^1*X4^1 + 462278*X1^3*X3^2 + 118688*X1^3*X2^1*X4^1 + 778905*X1^3*X2^1*X3^1 + 748059*X1^3*X2^2 + 100541*X1^4*X4^1 + 419138*X1^4*X3^1 + 456337*X1^4*X2^1 + 452022*X1^5;
lambda := F!472961;
H := N - lambda*D;
qrow := [ Derivative(q, index) : index in [1..4] ];
crow := [ Derivative(c, index) : index in [1..4] ];
mrow := [ D*Derivative(N, index) - N*Derivative(D, index) : index in [1..4] ];
W := [];
for selected in [1..4] do
    unit := [ P!0 : index in [1..4] ];
    unit[selected] := P!1;
    Append(~W, Determinant(Matrix(P, 4, 4, qrow cat crow cat mrow cat unit)));
end for;
critical_fibre := ideal<P | [q, c, H] cat W>;
hp, regularity := HilbertPolynomial(critical_fibre);
critical_ok := Degree(hp) eq 0 and Coefficient(hp, 0) eq 15;
all_critical_checks := all_critical_checks and critical_ok;
plane_ok, collision_free := CheckPlaneFibre(q, c, N, D, lambda, 6);
all_plane_checks := all_plane_checks and plane_ok;
if collision_free then
    Append(~collision_free_embeddings, 6);
end if;

// Residue embedding 7, a |-> 355128.
q := 0*X1*X1 + 0*X1*X2 + 1*X1*X3 + 1*X1*X4 + 863152*X2*X2 + 863152*X2*X3 + 765797*X2*X4 + 828069*X3*X3 + 407071*X3*X4 + 353299*X4*X4;
c := 0*X1*X1*X1 + 0*X1*X1*X2 + 0*X1*X1*X3 + 719570*X1*X1*X4 + 0*X1*X2*X2 + 0*X1*X2*X3 + 719570*X1*X2*X4 + 0*X1*X3*X3 + 0*X1*X3*X4 + 605237*X1*X4*X4 + 143583*X2*X2*X2 + 91941*X2*X2*X3 + 601383*X2*X2*X4 + 324876*X2*X3*X3 + 639416*X2*X3*X4 + 278274*X2*X4*X4 + 1*X3*X3*X3 + 325817*X3*X3*X4 + 262709*X3*X4*X4 + 566522*X4*X4*X4;
N := 1*X2^2*X3^3 + 407425*X2^4*X3^1 + 580674*X2^5 + 614505*X1^1*X2^1*X3^3 + 404934*X1^1*X2^2*X3^1*X4^1 + 519606*X1^1*X2^2*X3^2 + 235031*X1^1*X2^3*X4^1 + 214404*X1^1*X2^3*X3^1 + 61532*X1^1*X2^4 + 667107*X1^2*X3^3 + 197866*X1^2*X2^1*X3^1*X4^1 + 95038*X1^2*X2^1*X3^2 + 618842*X1^2*X2^2*X4^1 + 638230*X1^2*X2^2*X3^1 + 687830*X1^2*X2^3 + 464000*X1^3*X3^1*X4^1 + 663461*X1^3*X3^2 + 97433*X1^3*X2^1*X4^1 + 546656*X1^3*X2^1*X3^1 + 835503*X1^3*X2^2 + 491820*X1^4*X4^1 + 27650*X1^4*X3^1;
D := 1*X2^2*X3^3 + 457929*X2^3*X3^1*X4^1 + 832155*X2^3*X3^2 + 358983*X2^4*X4^1 + 365718*X2^4*X3^1 + 742278*X2^5 + 390308*X1^1*X2^1*X3^3 + 473906*X1^1*X2^2*X3^1*X4^1 + 512056*X1^1*X2^2*X3^2 + 101189*X1^1*X2^3*X4^1 + 167654*X1^1*X2^3*X3^1 + 80481*X1^1*X2^4 + 532903*X1^2*X3^3 + 404360*X1^2*X2^1*X3^1*X4^1 + 349431*X1^2*X2^1*X3^2 + 505594*X1^2*X2^2*X4^1 + 320377*X1^2*X2^2*X3^1 + 163310*X1^2*X2^3 + 559345*X1^3*X3^1*X4^1 + 750730*X1^3*X3^2 + 733364*X1^3*X2^1*X4^1 + 506417*X1^3*X2^1*X3^1 + 262871*X1^3*X2^2 + 484037*X1^4*X4^1 + 86682*X1^4*X3^1 + 53072*X1^4*X2^1 + 291809*X1^5;
lambda := F!688626;
H := N - lambda*D;
qrow := [ Derivative(q, index) : index in [1..4] ];
crow := [ Derivative(c, index) : index in [1..4] ];
mrow := [ D*Derivative(N, index) - N*Derivative(D, index) : index in [1..4] ];
W := [];
for selected in [1..4] do
    unit := [ P!0 : index in [1..4] ];
    unit[selected] := P!1;
    Append(~W, Determinant(Matrix(P, 4, 4, qrow cat crow cat mrow cat unit)));
end for;
critical_fibre := ideal<P | [q, c, H] cat W>;
hp, regularity := HilbertPolynomial(critical_fibre);
critical_ok := Degree(hp) eq 0 and Coefficient(hp, 0) eq 15;
all_critical_checks := all_critical_checks and critical_ok;
plane_ok, collision_free := CheckPlaneFibre(q, c, N, D, lambda, 7);
all_plane_checks := all_plane_checks and plane_ok;
if collision_free then
    Append(~collision_free_embeddings, 7);
end if;

// Residue embedding 8, a |-> 398915.
q := 0*X1*X1 + 0*X1*X2 + 1*X1*X3 + 1*X1*X4 + 863152*X2*X2 + 863152*X2*X3 + 6384*X2*X4 + 157692*X3*X3 + 728811*X3*X4 + 93197*X4*X4;
c := 0*X1*X1*X1 + 0*X1*X1*X2 + 0*X1*X1*X3 + 457583*X1*X1*X4 + 0*X1*X2*X2 + 0*X1*X2*X3 + 457583*X1*X2*X4 + 0*X1*X3*X3 + 0*X1*X3*X4 + 445965*X1*X4*X4 + 405570*X2*X2*X2 + 773477*X2*X2*X3 + 13717*X2*X2*X4 + 614262*X2*X3*X3 + 509036*X2*X3*X4 + 539102*X2*X4*X4 + 1*X3*X3*X3 + 107333*X3*X3*X4 + 139625*X3*X4*X4 + 547804*X4*X4*X4;
N := 1*X2^2*X3^3 + 489816*X2^4*X3^1 + 503139*X2^5 + 851635*X1^1*X2^1*X3^3 + 242771*X1^1*X2^2*X3^1*X4^1 + 548934*X1^1*X2^2*X3^2 + 326548*X1^1*X2^3*X4^1 + 812548*X1^1*X2^3*X3^1 + 710136*X1^1*X2^4 + 422179*X1^2*X3^3 + 401449*X1^2*X2^1*X3^1*X4^1 + 751723*X1^2*X2^1*X3^2 + 117163*X1^2*X2^2*X4^1 + 307219*X1^2*X2^2*X3^1 + 546191*X1^2*X2^3 + 135957*X1^3*X3^1*X4^1 + 320237*X1^3*X3^2 + 466293*X1^3*X2^1*X4^1 + 322101*X1^3*X2^1*X3^1 + 95553*X1^3*X2^2 + 858014*X1^4*X4^1 + 767600*X1^4*X3^1;
D := 1*X2^2*X3^3 + 775145*X2^3*X3^1*X4^1 + 191971*X2^3*X3^2 + 468936*X2^4*X4^1 + 471210*X2^4*X3^1 + 174759*X2^5 + 843593*X1^1*X2^1*X3^3 + 763371*X1^1*X2^2*X3^1*X4^1 + 830862*X1^1*X2^2*X3^2 + 699533*X1^1*X2^3*X4^1 + 209018*X1^1*X2^3*X3^1 + 762403*X1^1*X2^4 + 761948*X1^2*X3^3 + 784308*X1^2*X2^1*X3^1*X4^1 + 126402*X1^2*X2^1*X3^2 + 272415*X1^2*X2^2*X4^1 + 16343*X1^2*X2^2*X3^1 + 450285*X1^2*X2^3 + 438904*X1^3*X3^1*X4^1 + 419730*X1^3*X3^2 + 115366*X1^3*X2^1*X4^1 + 697651*X1^3*X2^1*X3^1 + 680012*X1^3*X2^2 + 793410*X1^4*X4^1 + 202554*X1^4*X3^1 + 63237*X1^4*X2^1 + 719968*X1^5;
lambda := F!609154;
H := N - lambda*D;
qrow := [ Derivative(q, index) : index in [1..4] ];
crow := [ Derivative(c, index) : index in [1..4] ];
mrow := [ D*Derivative(N, index) - N*Derivative(D, index) : index in [1..4] ];
W := [];
for selected in [1..4] do
    unit := [ P!0 : index in [1..4] ];
    unit[selected] := P!1;
    Append(~W, Determinant(Matrix(P, 4, 4, qrow cat crow cat mrow cat unit)));
end for;
critical_fibre := ideal<P | [q, c, H] cat W>;
hp, regularity := HilbertPolynomial(critical_fibre);
critical_ok := Degree(hp) eq 0 and Coefficient(hp, 0) eq 15;
all_critical_checks := all_critical_checks and critical_ok;
plane_ok, collision_free := CheckPlaneFibre(q, c, N, D, lambda, 8);
all_plane_checks := all_plane_checks and plane_ok;
if collision_free then
    Append(~collision_free_embeddings, 8);
end if;

// Residue embedding 9, a |-> 630744.
q := 0*X1*X1 + 0*X1*X2 + 1*X1*X3 + 1*X1*X4 + 863152*X2*X2 + 863152*X2*X3 + 494642*X2*X4 + 415005*X3*X3 + 190890*X3*X4 + 573822*X4*X4;
c := 0*X1*X1*X1 + 0*X1*X1*X2 + 0*X1*X1*X3 + 565660*X1*X1*X4 + 0*X1*X2*X2 + 0*X1*X2*X3 + 565660*X1*X2*X4 + 0*X1*X3*X3 + 0*X1*X3*X4 + 652641*X1*X4*X4 + 297493*X2*X2*X2 + 562464*X2*X2*X3 + 251191*X2*X2*X4 + 212007*X2*X3*X3 + 247368*X2*X3*X4 + 336572*X2*X4*X4 + 1*X3*X3*X3 + 82276*X3*X3*X4 + 596911*X3*X4*X4 + 821544*X4*X4*X4;
N := 1*X2^2*X3^3 + 405125*X2^4*X3^1 + 407330*X2^5 + 655136*X1^1*X2^1*X3^3 + 175088*X1^1*X2^2*X3^1*X4^1 + 278673*X1^1*X2^2*X3^2 + 509993*X1^1*X2^3*X4^1 + 124497*X1^1*X2^3*X3^1 + 261465*X1^1*X2^4 + 409279*X1^2*X3^3 + 556753*X1^2*X2^1*X3^1*X4^1 + 318931*X1^2*X2^1*X3^2 + 701153*X1^2*X2^2*X4^1 + 737020*X1^2*X2^2*X3^1 + 410464*X1^2*X2^3 + 684916*X1^3*X3^1*X4^1 + 462490*X1^3*X3^2 + 784727*X1^3*X2^1*X4^1 + 355988*X1^3*X2^1*X3^1 + 278331*X1^3*X2^2 + 96701*X1^4*X4^1 + 584822*X1^4*X3^1;
D := 1*X2^2*X3^3 + 770332*X2^3*X3^1*X4^1 + 381004*X2^3*X3^2 + 484279*X2^4*X4^1 + 569934*X2^4*X3^1 + 145617*X2^5 + 424041*X1^1*X2^1*X3^3 + 14198*X1^1*X2^2*X3^1*X4^1 + 750550*X1^1*X2^2*X3^2 + 332409*X1^1*X2^3*X4^1 + 748767*X1^1*X2^3*X3^1 + 299933*X1^1*X2^4 + 371246*X1^2*X3^3 + 474967*X1^2*X2^1*X3^1*X4^1 + 207667*X1^2*X2^1*X3^2 + 807055*X1^2*X2^2*X4^1 + 276426*X1^2*X2^2*X3^1 + 679492*X1^2*X2^3 + 255771*X1^3*X3^1*X4^1 + 415114*X1^3*X3^2 + 511514*X1^3*X2^1*X4^1 + 425730*X1^3*X2^1*X3^1 + 207880*X1^3*X2^2 + 761241*X1^4*X4^1 + 596686*X1^4*X3^1 + 205389*X1^4*X2^1 + 256475*X1^5;
lambda := F!597098;
H := N - lambda*D;
qrow := [ Derivative(q, index) : index in [1..4] ];
crow := [ Derivative(c, index) : index in [1..4] ];
mrow := [ D*Derivative(N, index) - N*Derivative(D, index) : index in [1..4] ];
W := [];
for selected in [1..4] do
    unit := [ P!0 : index in [1..4] ];
    unit[selected] := P!1;
    Append(~W, Determinant(Matrix(P, 4, 4, qrow cat crow cat mrow cat unit)));
end for;
critical_fibre := ideal<P | [q, c, H] cat W>;
hp, regularity := HilbertPolynomial(critical_fibre);
critical_ok := Degree(hp) eq 0 and Coefficient(hp, 0) eq 15;
all_critical_checks := all_critical_checks and critical_ok;
plane_ok, collision_free := CheckPlaneFibre(q, c, N, D, lambda, 9);
all_plane_checks := all_plane_checks and plane_ok;
if collision_free then
    Append(~collision_free_embeddings, 9);
end if;

// Residue embedding 10, a |-> 649613.
q := 0*X1*X1 + 0*X1*X2 + 1*X1*X3 + 1*X1*X4 + 863152*X2*X2 + 863152*X2*X3 + 280562*X2*X4 + 726037*X3*X3 + 126873*X3*X4 + 95393*X4*X4;
c := 0*X1*X1*X1 + 0*X1*X1*X2 + 0*X1*X1*X3 + 755057*X1*X1*X4 + 0*X1*X2*X2 + 0*X1*X2*X3 + 755057*X1*X2*X4 + 0*X1*X3*X3 + 0*X1*X3*X4 + 850824*X1*X4*X4 + 108096*X2*X2*X2 + 628116*X2*X2*X3 + 401227*X2*X2*X4 + 137882*X2*X3*X3 + 303114*X2*X3*X4 + 249928*X2*X4*X4 + 1*X3*X3*X3 + 310099*X3*X3*X4 + 451459*X3*X4*X4 + 408922*X4*X4*X4;
N := 1*X2^2*X3^3 + 178581*X2^4*X3^1 + 210380*X2^5 + 566183*X1^1*X2^1*X3^3 + 489641*X1^1*X2^2*X3^1*X4^1 + 602825*X1^1*X2^2*X3^2 + 661643*X1^1*X2^3*X4^1 + 327146*X1^1*X2^3*X3^1 + 379374*X1^1*X2^4 + 318338*X1^2*X3^3 + 804659*X1^2*X2^1*X3^1*X4^1 + 732739*X1^2*X2^1*X3^2 + 738576*X1^2*X2^2*X4^1 + 197921*X1^2*X2^2*X3^1 + 472116*X1^2*X2^3 + 428698*X1^3*X3^1*X4^1 + 198400*X1^3*X3^2 + 490835*X1^3*X2^1*X4^1 + 374330*X1^3*X2^1*X3^1 + 47355*X1^3*X2^2 + 16707*X1^4*X4^1 + 815798*X1^4*X3^1;
D := 1*X2^2*X3^3 + 65949*X2^3*X3^1*X4^1 + 818335*X2^3*X3^2 + 600014*X2^4*X4^1 + 626912*X2^4*X3^1 + 380073*X2^5 + 559247*X1^1*X2^1*X3^3 + 446643*X1^1*X2^2*X3^1*X4^1 + 50087*X1^1*X2^2*X3^2 + 789343*X1^1*X2^3*X4^1 + 700008*X1^1*X2^3*X3^1 + 694600*X1^1*X2^4 + 332089*X1^2*X3^3 + 268625*X1^2*X2^1*X3^1*X4^1 + 296672*X1^2*X2^1*X3^2 + 494528*X1^2*X2^2*X4^1 + 467012*X1^2*X2^2*X3^1 + 426800*X1^2*X2^3 + 373330*X1^3*X3^1*X4^1 + 356239*X1^3*X3^2 + 18855*X1^3*X2^1*X4^1 + 266773*X1^3*X2^1*X3^1 + 637911*X1^3*X2^2 + 46553*X1^4*X4^1 + 594597*X1^4*X3^1 + 664492*X1^4*X2^1 + 190704*X1^5;
lambda := F!686461;
H := N - lambda*D;
qrow := [ Derivative(q, index) : index in [1..4] ];
crow := [ Derivative(c, index) : index in [1..4] ];
mrow := [ D*Derivative(N, index) - N*Derivative(D, index) : index in [1..4] ];
W := [];
for selected in [1..4] do
    unit := [ P!0 : index in [1..4] ];
    unit[selected] := P!1;
    Append(~W, Determinant(Matrix(P, 4, 4, qrow cat crow cat mrow cat unit)));
end for;
critical_fibre := ideal<P | [q, c, H] cat W>;
hp, regularity := HilbertPolynomial(critical_fibre);
critical_ok := Degree(hp) eq 0 and Coefficient(hp, 0) eq 15;
all_critical_checks := all_critical_checks and critical_ok;
plane_ok, collision_free := CheckPlaneFibre(q, c, N, D, lambda, 10);
all_plane_checks := all_plane_checks and plane_ok;
if collision_free then
    Append(~collision_free_embeddings, 10);
end if;

// Residue embedding 11, a |-> 785708.
q := 0*X1*X1 + 0*X1*X2 + 1*X1*X3 + 1*X1*X4 + 863152*X2*X2 + 863152*X2*X3 + 428214*X2*X4 + 862043*X3*X3 + 732799*X3*X4 + 416135*X4*X4;
c := 0*X1*X1*X1 + 0*X1*X1*X2 + 0*X1*X1*X3 + 398628*X1*X1*X4 + 0*X1*X2*X2 + 0*X1*X2*X3 + 398628*X1*X2*X4 + 0*X1*X3*X3 + 0*X1*X3*X4 + 745853*X1*X4*X4 + 464525*X2*X2*X2 + 236995*X2*X2*X3 + 857958*X2*X2*X4 + 574421*X2*X3*X3 + 561392*X2*X3*X4 + 307555*X2*X4*X4 + 1*X3*X3*X3 + 181414*X3*X3*X4 + 526438*X3*X4*X4 + 585824*X4*X4*X4;
N := 1*X2^2*X3^3 + 308734*X2^4*X3^1 + 463371*X2^5 + 652422*X1^1*X2^1*X3^3 + 859175*X1^1*X2^2*X3^1*X4^1 + 506640*X1^1*X2^2*X3^2 + 370560*X1^1*X2^3*X4^1 + 365845*X1^1*X2^3*X3^1 + 631337*X1^1*X2^4 + 32542*X1^2*X3^3 + 356650*X1^2*X2^1*X3^1*X4^1 + 406165*X1^2*X2^1*X3^2 + 375953*X1^2*X2^2*X4^1 + 597924*X1^2*X2^2*X3^1 + 828167*X1^2*X2^3 + 169474*X1^3*X3^1*X4^1 + 151290*X1^3*X3^2 + 802403*X1^3*X2^1*X4^1 + 595392*X1^3*X2^1*X3^1 + 211060*X1^3*X2^2 + 302747*X1^4*X4^1 + 652093*X1^4*X3^1;
D := 1*X2^2*X3^3 + 764144*X2^3*X3^1*X4^1 + 254209*X2^3*X3^2 + 8973*X2^4*X4^1 + 434526*X2^4*X3^1 + 401590*X2^5 + 158688*X1^1*X2^1*X3^3 + 555263*X1^1*X2^2*X3^1*X4^1 + 609357*X1^1*X2^2*X3^2 + 106953*X1^1*X2^3*X4^1 + 55604*X1^1*X2^3*X3^1 + 68901*X1^1*X2^4 + 286725*X1^2*X3^3 + 818479*X1^2*X2^1*X3^1*X4^1 + 621238*X1^2*X2^1*X3^2 + 758442*X1^2*X2^2*X4^1 + 699784*X1^2*X2^2*X3^1 + 416988*X1^2*X2^3 + 65251*X1^3*X3^1*X4^1 + 266948*X1^3*X3^2 + 737584*X1^3*X2^1*X4^1 + 578659*X1^3*X2^1*X3^1 + 166514*X1^3*X2^2 + 52915*X1^4*X4^1 + 68147*X1^4*X3^1 + 622964*X1^4*X2^1 + 778216*X1^5;
lambda := F!798676;
H := N - lambda*D;
qrow := [ Derivative(q, index) : index in [1..4] ];
crow := [ Derivative(c, index) : index in [1..4] ];
mrow := [ D*Derivative(N, index) - N*Derivative(D, index) : index in [1..4] ];
W := [];
for selected in [1..4] do
    unit := [ P!0 : index in [1..4] ];
    unit[selected] := P!1;
    Append(~W, Determinant(Matrix(P, 4, 4, qrow cat crow cat mrow cat unit)));
end for;
critical_fibre := ideal<P | [q, c, H] cat W>;
hp, regularity := HilbertPolynomial(critical_fibre);
critical_ok := Degree(hp) eq 0 and Coefficient(hp, 0) eq 15;
all_critical_checks := all_critical_checks and critical_ok;
plane_ok, collision_free := CheckPlaneFibre(q, c, N, D, lambda, 11);
all_plane_checks := all_plane_checks and plane_ok;
if collision_free then
    Append(~collision_free_embeddings, 11);
end if;

// Residue embedding 12, a |-> 805121.
q := 0*X1*X1 + 0*X1*X2 + 1*X1*X3 + 1*X1*X4 + 863152*X2*X2 + 863152*X2*X3 + 518101*X2*X4 + 722043*X3*X3 + 677664*X3*X4 + 704424*X4*X4;
c := 0*X1*X1*X1 + 0*X1*X1*X2 + 0*X1*X1*X3 + 576416*X1*X1*X4 + 0*X1*X2*X2 + 0*X1*X2*X3 + 576416*X1*X2*X4 + 0*X1*X3*X3 + 0*X1*X3*X4 + 309019*X1*X4*X4 + 286737*X2*X2*X2 + 648612*X2*X2*X3 + 628944*X2*X2*X4 + 415367*X2*X3*X3 + 63667*X2*X3*X4 + 786004*X2*X4*X4 + 1*X3*X3*X3 + 650576*X3*X3*X4 + 477634*X3*X4*X4 + 519521*X4*X4*X4;
N := 1*X2^2*X3^3 + 32573*X2^4*X3^1 + 398210*X2^5 + 696077*X1^1*X2^1*X3^3 + 471330*X1^1*X2^2*X3^1*X4^1 + 238791*X1^1*X2^2*X3^2 + 477991*X1^1*X2^3*X4^1 + 407584*X1^1*X2^3*X3^1 + 734481*X1^1*X2^4 + 284747*X1^2*X3^3 + 370700*X1^2*X2^1*X3^1*X4^1 + 636563*X1^2*X2^1*X3^2 + 548551*X1^2*X2^2*X4^1 + 323175*X1^2*X2^2*X3^1 + 128806*X1^2*X2^3 + 152727*X1^3*X3^1*X4^1 + 652509*X1^3*X3^2 + 508334*X1^3*X2^1*X4^1 + 479575*X1^3*X2^1*X3^1 + 159538*X1^3*X2^2 + 254772*X1^4*X4^1 + 703615*X1^4*X3^1;
D := 1*X2^2*X3^3 + 127487*X2^3*X3^1*X4^1 + 809543*X2^3*X3^2 + 183673*X2^4*X4^1 + 216088*X2^4*X3^1 + 252733*X2^5 + 178309*X1^1*X2^1*X3^3 + 251831*X1^1*X2^2*X3^1*X4^1 + 79658*X1^1*X2^2*X3^2 + 189785*X1^1*X2^3*X4^1 + 27676*X1^1*X2^3*X3^1 + 800565*X1^1*X2^4 + 679009*X1^2*X3^3 + 362809*X1^2*X2^1*X3^1*X4^1 + 218861*X1^2*X2^1*X3^2 + 261658*X1^2*X2^2*X4^1 + 245453*X1^2*X2^2*X3^1 + 325613*X1^2*X2^3 + 449151*X1^3*X3^1*X4^1 + 659969*X1^3*X3^2 + 551477*X1^3*X2^1*X4^1 + 472196*X1^3*X2^1*X3^1 + 809177*X1^3*X2^2 + 849529*X1^4*X4^1 + 509624*X1^4*X3^1 + 820744*X1^4*X2^1 + 489245*X1^5;
lambda := F!667681;
H := N - lambda*D;
qrow := [ Derivative(q, index) : index in [1..4] ];
crow := [ Derivative(c, index) : index in [1..4] ];
mrow := [ D*Derivative(N, index) - N*Derivative(D, index) : index in [1..4] ];
W := [];
for selected in [1..4] do
    unit := [ P!0 : index in [1..4] ];
    unit[selected] := P!1;
    Append(~W, Determinant(Matrix(P, 4, 4, qrow cat crow cat mrow cat unit)));
end for;
critical_fibre := ideal<P | [q, c, H] cat W>;
hp, regularity := HilbertPolynomial(critical_fibre);
critical_ok := Degree(hp) eq 0 and Coefficient(hp, 0) eq 15;
all_critical_checks := all_critical_checks and critical_ok;
plane_ok, collision_free := CheckPlaneFibre(q, c, N, D, lambda, 12);
all_plane_checks := all_plane_checks and plane_ok;
if collision_free then
    Append(~collision_free_embeddings, 12);
end if;

if all_critical_checks and all_plane_checks and #collision_free_embeddings gt 0 then
print "PASS Magma: critical-fibre length 15 in all 12 embeddings modulo 863153";
print "PASS Magma: seven base points plus eight residual ramification points";
print "PASS Magma: collision-free residue embeddings", collision_free_embeddings;
print "PASS Magma: good reduction excludes characteristic-zero projected-point collisions";
else
    error "Hurwitz geometry certificate failed";
end if;
quit;
