#!/usr/bin/env python3
"""Generate the independent Magma check for the exact third branch value."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "hurwitz_degree23_branch_candidate.json"
OUTPUT = ROOT / "verification" / "verify_hurwitz_degree23_branch.m"


def q(record):
    numerator = int(record["numerator"])
    denominator = int(record["denominator"])
    return str(numerator) if denominator == 1 else f"({numerator}/{denominator})"


def render(payload):
    coefficients = payload["field"]["defining_polynomial_coefficients_ascending"]
    denominator = int(payload["lambda"]["denominator"])
    numerators = [int(value) for value in payload["lambda"]["power_basis_numerators"]]
    holdouts = payload["independent_holdouts"]["records"]
    lines = [
        "// Generated by scripts/emit_hurwitz_degree23_magma_certificate.py.",
        "// Independent arithmetic check of the reconstructed third branch value.",
        "",
        "procedure Must(condition, message)",
        "    if not condition then error message; end if;",
        "end procedure;",
        "",
        "Qx<x> := PolynomialRing(Rationals());",
        "f := " + " + ".join(
            f"({q(value)})*x^{index}" for index, value in enumerate(coefficients)
        ) + ";",
        "Must(IsIrreducible(f), \"absolute Hurwitz field polynomial is reducible\");",
        "K<a> := NumberField(f);",
        f"denominator := {denominator};",
        "numerators := [",
    ]
    lines.extend(f"    {value}{',' if index + 1 < len(numerators) else ''}" for index, value in enumerate(numerators))
    lines.extend([
        "];",
        "lambda := &+[ (Rationals()!numerators[index])/denominator * a^(index-1) : index in [1..12] ];",
        "Must(lambda ne 0, \"third branch value is zero\");",
        "Must(Degree(MinimalPolynomial(lambda)) eq 12, \"third branch value is not primitive\");",
        "",
        "records := [",
    ])
    items = sorted(((int(prime), values) for prime, values in holdouts.items()))
    for index, (prime, values) in enumerate(items):
        suffix = "," if index + 1 < len(items) else ""
        lines.append(f"    <{prime}, [{', '.join(map(str, values))}]>{suffix}")
    lines.extend([
        "];",
        "for record in records do",
        "    prime := record[1];",
        "    expected := record[2];",
        "    F := GF(prime);",
        "    Fa<abar> := PolynomialRing(F);",
        "    fp := &+[ (F!(Numerator(coefficients[index])))/(F!(Denominator(coefficients[index]))) * abar^(index-1) : index in [1..13] ]",
        "        where coefficients := Coefficients(f);",
        "    Must(#Roots(fp) eq 12, Sprintf(\"field does not split at %o\", prime));",
        "    actual := [ Integers()!((F!value)/(F!denominator)) : value in numerators ];",
        "    Must(actual eq expected, Sprintf(\"holdout mismatch at %o\", prime));",
        "end for;",
        "",
        'print "PASS Magma: irreducible degree-12 Hurwitz field";',
        'print "PASS Magma: primitive exact third branch value";',
        f'print "PASS Magma: {len(items)} independent split-prime holdouts";',
        "quit;",
        "",
    ])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    rendered = render(json.loads(SOURCE.read_text()))
    if arguments.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
            raise SystemExit(f"{OUTPUT} is stale; regenerate without --check")
        print(f"PASS deterministic Magma certificate {OUTPUT}")
    else:
        OUTPUT.write_text(rendered)
        print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
