#!/usr/bin/env python3
"""Generate a Magma check of the six-cover critical-fibre geometry modulo p."""

from __future__ import annotations

import argparse
from fractions import Fraction
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CANONICAL_PATH = ROOT / "data" / "hurwitz_canonical_models_candidate.json"
MAPS_PATH = ROOT / "data" / "hurwitz_degree23_maps_candidate.json"
BRANCH_PATH = ROOT / "data" / "hurwitz_degree23_branch_candidate.json"
OUTPUT = ROOT / "verification" / "verify_hurwitz_degree23_geometry.m"
PRIME = 863153


def rational(record):
    return Fraction(int(record["numerator"]), int(record["denominator"]))


def add_vectors(left, right):
    return [a + b for a, b in zip(left, right)]


def scale_vector(value, vector):
    return [value * coordinate for coordinate in vector]


def modular(value, prime):
    return value.numerator * pow(value.denominator, -1, prime) % prime


def evaluate_power_basis(coordinates, root, prime):
    total = 0
    power = 1
    for coordinate in coordinates:
        total = (total + modular(coordinate, prime) * power) % prime
        power = power * root % prime
    return total


def polynomial_value(coefficients, value, prime):
    total = 0
    for coefficient in reversed(coefficients):
        total = (total * value + modular(coefficient, prime)) % prime
    return total


def render_indexed_form(monomials, coefficients):
    terms = []
    for monomial, coefficient in zip(monomials, coefficients):
        factors = [str(coefficient)] + [f"X{index + 1}" for index in monomial]
        terms.append("*".join(factors))
    return " + ".join(terms) or "P!0"


def render_exponent_form(records, root, prime):
    terms = []
    for record in records:
        coefficient = evaluate_power_basis(
            [rational(value) for value in record["coefficient_power_basis"]],
            root,
            prime,
        )
        factors = [str(coefficient)]
        for index, exponent in enumerate(record["monomial"]):
            if exponent:
                factors.append(f"X{index + 1}^{exponent}")
        terms.append("*".join(factors))
    return " + ".join(terms) or "P!0"


def render():
    canonical = json.loads(CANONICAL_PATH.read_text())
    maps = json.loads(MAPS_PATH.read_text())
    branch = json.loads(BRANCH_PATH.read_text())
    field_coefficients = [
        rational(value)
        for value in canonical["absolute_field_polynomial_coefficients_ascending"]
    ]
    roots = [
        value
        for value in range(PRIME)
        if polynomial_value(field_coefficients, value, PRIME) == 0
    ]
    if len(roots) != 12:
        raise ValueError(f"expected 12 roots modulo {PRIME}, found {len(roots)}")

    integral_basis = [
        [rational(value) for value in basis]
        for basis in canonical["integral_basis_power_coefficients"]
    ]

    def curve_power_coordinates(record):
        coordinates = [Fraction(0)] * 12
        for scalar_record, basis in zip(
            record["sextic_component"]["integral_basis_coordinates"],
            integral_basis,
        ):
            coordinates = add_vectors(
                coordinates, scale_vector(rational(scalar_record), basis)
            )
        return coordinates

    quadric_power = [
        curve_power_coordinates(value)
        for value in canonical["quadric"]["coefficients"]
    ]
    cubic_power = [
        curve_power_coordinates(value)
        for value in canonical["petri_cubic"]["coefficients"]
    ]
    sextic_map = next(
        value for value in maps["components"] if value["component"] == "sextic"
    )
    lambda_power = [
        Fraction(int(value), int(branch["lambda"]["denominator"]))
        for value in branch["lambda"]["power_basis_numerators"]
    ]

    lines = [
        "// Generated by scripts/emit_hurwitz_degree23_magma_geometry_certificate.py.",
        "// Independent finite-field check of all twelve embeddings of the sextic component.",
        "",
        "procedure Must(condition, message)",
        "    if not condition then error message; end if;",
        "end procedure;",
        "",
        f"F := GF({PRIME});",
        "P<X1,X2,X3,X4> := PolynomialRing(F, 4, \"grevlex\");",
        "",
        "function CheckPlaneFibre(q, c, N, D, lambda, embedding)",
        "    A<x,y> := PolynomialRing(F, 2);",
        "    FF := FieldOfFractions(A);",
        "    Z<z> := PolynomialRing(FF);",
        "    qz := Evaluate(q, [Z!1, Z!x, Z!y, z]);",
        "    cz := Evaluate(c, [Z!1, Z!x, Z!y, z]);",
        "    remainder := cz mod qz;",
        "    if Degree(remainder) ne 1 then return false, false; end if;",
        "    zvalue := -Coefficient(remainder, 0)/Coefficient(remainder, 1);",
        "    plane := A!Numerator(Resultant(qz, cz));",
        "    nfraction := Evaluate(N, [Z!1, Z!x, Z!y, Z!zvalue]);",
        "    dfraction := Evaluate(D, [Z!1, Z!x, Z!y, Z!zvalue]);",
        "    mapfraction := FF!(nfraction/dfraction);",
        "    nplane := A!Numerator(mapfraction);",
        "    dplane := A!Denominator(mapfraction);",
        "    U<u> := PolynomialRing(F);",
        "    generic_raw := Resultant(plane, nplane - 2*dplane, 2);",
        "    generic_resultant := Evaluate(generic_raw, [u, U!0]);",
        "    branch_plane := nplane - lambda*dplane;",
        "    branch_raw := Resultant(plane, branch_plane, 2);",
        "    branch_resultant := Evaluate(branch_raw, [u, U!0]);",
        "    generic_gcd := GCD(generic_resultant, Derivative(generic_resultant));",
        "    branch_gcd := GCD(branch_resultant, Derivative(branch_resultant));",
        "    common_gcd := GCD(generic_gcd, branch_gcd);",
        "    extra_gcd := branch_gcd div common_gcd;",
        "    geometry_ok := Degree(generic_resultant) eq 42",
        "        and Degree(branch_resultant) eq 42",
        "        and Degree(generic_gcd) eq 6",
        "        and Degree(branch_gcd) eq 14",
        "        and Degree(common_gcd) eq 6",
        "        and Degree(extra_gcd) eq 8",
        "        and GCD(extra_gcd, Derivative(extra_gcd)) eq 1;",
        "    if not geometry_ok then return false, false; end if;",
        "    collision_free := true;",
        "    for item in Factorization(extra_gcd) do",
        "        h := item[1];",
        "        E<alpha> := ext<F | h>;",
        "        V<v> := PolynomialRing(E);",
        "        plane_at_alpha := Evaluate(plane, [V!alpha, v]);",
        "        branch_at_alpha := Evaluate(branch_plane, [V!alpha, v]);",
        "        common_y := GCD(plane_at_alpha, branch_at_alpha);",
        "        if Degree(common_y) ne 1 then collision_free := false; end if;",
        "    end for;",
        "    return true, collision_free;",
        "end function;",
        "",
        "all_critical_checks := true;",
        "all_plane_checks := true;",
        "collision_free_embeddings := [];",
        "",
    ]
    for embedding, root in enumerate(roots, 1):
        quadric_coefficients = [
            evaluate_power_basis(value, root, PRIME) for value in quadric_power
        ]
        cubic_coefficients = [
            evaluate_power_basis(value, root, PRIME) for value in cubic_power
        ]
        lambda_value = evaluate_power_basis(lambda_power, root, PRIME)
        lines.extend([
            f"// Residue embedding {embedding}, a |-> {root}.",
            "q := " + render_indexed_form(
                canonical["quadric"]["monomials"], quadric_coefficients
            ) + ";",
            "c := " + render_indexed_form(
                canonical["petri_cubic"]["monomials"], cubic_coefficients
            ) + ";",
            "N := " + render_exponent_form(
                sextic_map["numerator"], root, PRIME
            ) + ";",
            "D := " + render_exponent_form(
                sextic_map["denominator"], root, PRIME
            ) + ";",
            f"lambda := F!{lambda_value};",
            "H := N - lambda*D;",
            "qrow := [ Derivative(q, index) : index in [1..4] ];",
            "crow := [ Derivative(c, index) : index in [1..4] ];",
            "mrow := [ D*Derivative(N, index) - N*Derivative(D, index) : index in [1..4] ];",
            "W := [];",
            "for selected in [1..4] do",
            "    unit := [ P!0 : index in [1..4] ];",
            "    unit[selected] := P!1;",
            "    Append(~W, Determinant(Matrix(P, 4, 4, qrow cat crow cat mrow cat unit)));",
            "end for;",
            "critical_fibre := ideal<P | [q, c, H] cat W>;",
            "hp, regularity := HilbertPolynomial(critical_fibre);",
            "critical_ok := Degree(hp) eq 0 and Coefficient(hp, 0) eq 15;",
            "all_critical_checks := all_critical_checks and critical_ok;",
            f"plane_ok, collision_free := CheckPlaneFibre(q, c, N, D, lambda, {embedding});",
            "all_plane_checks := all_plane_checks and plane_ok;",
            "if collision_free then",
            f"    Append(~collision_free_embeddings, {embedding});",
            "end if;",
            "",
        ])
    lines.extend([
        'if all_critical_checks and all_plane_checks and #collision_free_embeddings gt 0 then',
        f'print "PASS Magma: critical-fibre length 15 in all 12 embeddings modulo {PRIME}";',
        'print "PASS Magma: seven base points plus eight residual ramification points";',
        'print "PASS Magma: collision-free residue embeddings", collision_free_embeddings;',
        'print "PASS Magma: good reduction excludes characteristic-zero projected-point collisions";',
        'else',
        '    error "Hurwitz geometry certificate failed";',
        'end if;',
        "quit;",
        "",
    ])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    rendered = render()
    if arguments.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
            raise SystemExit(f"{OUTPUT} is stale; regenerate without --check")
        print(f"PASS deterministic Magma geometry certificate {OUTPUT}")
    else:
        OUTPUT.write_text(rendered)
        print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
